import { Stack, Validations } from 'aws-cdk-lib';

/**
 * cdk-nag (AwsSolutions pack) findings we accept, each with the reason. Anything not listed here
 * fails `cdk synth`, so a new risky resource can't slip in unnoticed.
 */
const ACKNOWLEDGED: { id: string; reason: string }[] = [
  // ---- IAM: every role is also capped by the platform permission boundary ----
  {
    id: 'AwsSolutions-IAM4[Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole]',
    reason: 'AWS-managed policy that only allows writing CloudWatch Logs.',
  },
  {
    id: 'AwsSolutions-IAM5[Resource::*]',
    reason: 'X-Ray, CloudWatch log delivery and Step Functions task-token APIs do not support resource-level permissions.',
  },
  {
    id: 'AwsSolutions-IAM5[Resource::<RequestsC42AC379.Arn>/index/*]',
    reason: 'Query access to the two GSIs of the requests table only (generated by table.grant).',
  },
  {
    id: 'AwsSolutions-IAM5[Resource::<WorkflowValidateFn6BB603F3.Arn>:*]',
    reason: 'Step Functions may invoke any version/alias of its own validate function.',
  },
  {
    id: 'AwsSolutions-IAM5[Resource::<WorkflowRegisterApprovalFnFCEAD708.Arn>:*]',
    reason: 'Step Functions may invoke any version/alias of its own register-approval function.',
  },
  {
    id: 'AwsSolutions-IAM5[Resource::<WorkflowRevokeSessionsFn2D40A539.Arn>:*]',
    reason: 'Step Functions may invoke any version/alias of its own revoke-sessions function.',
  },
  ...['s3:Abort*', 's3:DeleteObject*', 's3:GetBucket*', 's3:GetObject*', 's3:List*'].map((action) => ({
    id: `AwsSolutions-IAM5[Action::${action}]`,
    reason: 'CDK BucketDeployment syncs the web build into the site bucket; scoped to that bucket and the CDK assets bucket.',
  })),
  {
    id: 'AwsSolutions-IAM5[Resource::<WebSiteBucket1E6F6F45.Arn>/*]',
    reason: 'BucketDeployment writes every object of the web build.',
  },
  {
    id: 'AwsSolutions-IAM5[Resource::arn:<AWS::Partition>:s3:::cdk-hnb659fds-assets-232936223811-eu-west-2/*]',
    reason: 'BucketDeployment reads the uploaded web build from the CDK assets bucket.',
  },
  {
    id: 'AwsSolutions-IAM5[Resource::arn:aws:iam::232936223811:role/jit-target-*]',
    reason: 'Session broker may assume only the platform-owned jit-target-* roles (also capped by the boundary).',
  },
  // ---- Lambda ----
  {
    id: 'AwsSolutions::AwsSolutions-L1',
    reason: 'Python 3.12 matches the pinned Powertools layer and the tested runtime; Node 22 is LTS. CDK BucketDeployment picks its own runtime.',
  },
  // ---- Queues ----
  { id: 'AwsSolutions::AwsSolutions-SQS3', reason: 'These queues ARE the dead-letter queues.' },
  // ---- Web edge: acceptable for a demo, listed as production follow-ups in docs ----
  { id: 'AwsSolutions::AwsSolutions-S1', reason: 'Bucket is only read by CloudFront via OAC; access is logged at the edge in production.' },
  { id: 'AwsSolutions::AwsSolutions-CFR1', reason: 'Internal tool without geographic restrictions.' },
  { id: 'AwsSolutions::AwsSolutions-CFR2', reason: 'Production follow-up: attach AWS WAF with managed rules and rate limiting.' },
  { id: 'AwsSolutions::AwsSolutions-CFR3', reason: 'Production follow-up: CloudFront standard logs to CloudWatch.' },
  { id: 'AwsSolutions::AwsSolutions-CFR4', reason: 'Default CloudFront domain; production uses a custom domain with ACM and TLSv1.2_2021.' },
  // ---- Cognito ----
  { id: 'AwsSolutions::AwsSolutions-COG2', reason: 'Demo users. Production: enforce MFA or federate to the corporate IdP that enforces it.' },
  { id: 'AwsSolutions::AwsSolutions-COG8', reason: 'Plus feature plan (threat protection) not needed for a demo; production follow-up.' },
];

export function applyNagSuppressions(stack: Stack): void {
  for (const rule of ACKNOWLEDGED) Validations.of(stack).acknowledge(rule);
}
